{
 "title": "Proxmox",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pve_node",
    "label": "Proxmox Node",
    "query": {
     "query": "label_values(pve_node_info, name)"
    }
   },
   {
    "name": "guest_type",
    "query": {
     "query": "label_values(pve_guest_info, type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Host metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio / pve_cpu_usage_limit and on(id) pve_node_info{name=~\"$pve_node\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes / pve_memory_size_bytes and on(id) pve_node_info{name=~\"$pve_node\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{id=~\"storage/$pve_node.+\"} / pve_disk_size_bytes * on (id, instance) group_left(storage) pve_storage_info",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Space allocation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pve_disk_size_bytes{id=~\"storage/$pve_node.+\"} * on (id, instance) group_left(storage) pve_storage_info",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Resource metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resource summary",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by (id, name, type) (pve_guest_info{template!=\"1\",type=~\"$guest_type\"})"
      },
      {
       "expr": "sum by (id) (pve_up{template!=\"1\"} and on (id, instance) pve_guest_info{type=~\"$guest_type\"})"
      },
      {
       "expr": "sum by (id) (pve_cpu_usage_limit{template!=\"1\"} and on (id, instance) pve_guest_info{type=~\"$guest_type\"})"
      },
      {
       "expr": "sum by (id) (pve_memory_size_bytes{template!=\"1\"} and on (id, instance) pve_guest_info{type=~\"$guest_type\"})"
      },
      {
       "expr": "sum by (id) (pve_memory_usage_bytes{template!=\"1\"} / pve_memory_size_bytes and on (id, instance) pve_guest_info{type=~\"$guest_type\"})"
      },
      {
       "expr": "sum by (id) (pve_disk_size_bytes{template!=\"1\"} and on (id, instance) pve_guest_info{type=~\"$guest_type\"})"
      },
      {
       "expr": "sum by (id) (pve_disk_usage_bytes{template!=\"1\"} / pve_disk_size_bytes and on (id, instance) pve_guest_info{type=~\"$guest_type\"})"
      }
     ]
    },
    {
     "title": "resources with high cpu usage",
     "type": "stat",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count((pve_cpu_usage_ratio / pve_cpu_usage_limit) > 0.75)"
      }
     ]
    },
    {
     "title": "Guests CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 20, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "((pve_cpu_usage_ratio / pve_cpu_usage_limit) * on(id, instance) group_left(name, type) pve_guest_info{type=~\"$guest_type\"}) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} ({{type}})"
      }
     ]
    },
    {
     "title": "resources with high memory usage",
     "type": "stat",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count((pve_memory_usage_bytes / pve_memory_size_bytes) > 0.75)"
      }
     ]
    },
    {
     "title": "Guests memory usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 20, "x": 4, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(pve_memory_usage_bytes / pve_memory_size_bytes * on(id, instance) group_left(name, type) pve_guest_info{type=~\"$guest_type\"}) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} ({{type}})"
      }
     ]
    },
    {
     "title": "resources with high memory usage",
     "type": "stat",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count((pve_disk_usage_bytes / pve_disk_size_bytes) > 0.75)"
      }
     ]
    },
    {
     "title": "Guests Disk usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 20, "x": 4, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "pve_disk_usage_bytes / pve_disk_size_bytes * on (id, instance) group_left(name, type) pve_guest_info{type=~\"$guest_type\"}",
       "legendFormat": "{{name}} ({{type}})"
      }
     ]
    },
    {
     "title": "Disk IO/s",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "((rate(pve_disk_write_bytes[5m]) + rate(pve_disk_read_bytes[5m])) * on(id, instance) group_left(name, type) pve_guest_info{type=~\"$guest_type\"}) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} ({{type}})"
      }
     ]
    },
    {
     "title": "Network IO/s",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(rate(pve_network_receive_bytes[5m]) * on(id, instance) group_left(name, type) pve_guest_info{type=~\"$guest_type\"}) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} RECV ({{type}})"
      },
      {
       "expr": "(rate(pve_network_transmit_bytes[5m])* on(id, instance) group_left(name, type) pve_guest_info{type=~\"$guest_type\"}) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} SEND ({{type}})"
      }
     ]
    }
   ]
  }
 ]
}