{
 "title": "OPNSense Firewall",
 "description": "Dashboard using Prometheus Exporter built in OPNSense Appliance designed to be used with PMM v2",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "Host:",
    "query": {
     "query": "label_values(up{application=\"opnsense\"}, instance)"
    }
   },
   {
    "name": "port",
    "label": "port",
    "query": {
     "query": "label_values(up{job=~\"node_.*\"}, instance)"
    }
   },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,1h,6h,1d" },
   {
    "name": "cpus",
    "label": "cpus",
    "query": {
     "query": "label_values(node_cpu_seconds_total{instance=~\"$instance:.+\",job=~\"node_$instance\"}, cpu)"
    }
   },
   {
    "name": "mountpoint",
    "label": "mountpoint",
    "query": {
     "query": "label_values(node_filesystem_size{instance=~\"$instance:$port\"}, mountpoint)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic CPU / Mem / Disk Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",instance=\"$node_name\"}[30s])) / count(count(node_cpu_seconds_total{instance=\"$node_name\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_active_bytes{instance=\"$node_name\"} + node_memory_wired_bytes{instance=\"$node_name\"}) / node_memory_size_bytes{instance=\"$node_name\"}) * 100"
    }
   ]
  },
  {
   "title": "Normalised LA (1m avg)",
   "type": "gauge",
   "description": "LA / CPU count (1 min average)",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$node_name\"} / scalar(count(count(node_cpu_seconds_total{instance=\"$node_name\"}) by (cpu)))"
    }
   ]
  },
  {
   "title": "Normalised LA (15m avg)",
   "type": "gauge",
   "description": "LA / CPU count (15m avg)",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load15{instance=\"$node_name\"} / scalar(count(count(node_cpu_seconds_total{instance=\"$node_name\"}) by (cpu)))"
    }
   ]
  },
  {
   "title": "Used disk $mountpoint",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "repeat": "mountpoint",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$node_name\",mountpoint=~\"/\"} - node_filesystem_avail_bytes{instance=\"$node_name\",mountpoint=~\"/\"}) / node_filesystem_size_bytes{instance=\"$node_name\",mountpoint=~\"/\"} * 100"
    }
   ]
  },
  {
   "title": "Inodes used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "repeat": "mountpoint",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_files{instance=\"$node_name\",mountpoint=~\"/\"} - node_filesystem_files_free{instance=\"$node_name\",mountpoint=~\"/\"}) / node_filesystem_files{instance=\"$node_name\",mountpoint=~\"/\"} * 100"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node_name\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_size_bytes{instance=\"$node_name\"}"
    }
   ]
  },
  {
   "title": "Total active Mem",
   "type": "stat",
   "description": "Total active mem",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_active_bytes{instance=\"$node_name\"}"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node_name\", mountpoint=\"/\"}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Network Traffic / sec",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node_name\"}[$interval]) * 8  > 0",
     "legendFormat": "{{device}} recv"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node_name\"}[$interval]) * 8  > 0",
     "legendFormat": "{{device}} trans"
    }
   ]
  },
  {
   "title": "Network packets / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{instance=\"$node_name\"}[$interval]) > 0",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{instance=\"$node_name\"}[$interval]) > 0",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "repeat": "mountpoint",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node_name\",mountpoint=~\"/\"} - node_filesystem_avail_bytes{instance=\"$node_name\",mountpoint=~\"/\"}",
     "legendFormat": "Used {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node_name\",mountpoint=~\"/\"}",
     "legendFormat": "Total {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Mcast packets / sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_multicast_total{instance=~\"$node_name\"}[$interval]) > 0",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_multicast_total{instance=~\"$node_name\"}[$interval]) > 0",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "RAM detailed allocation",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_size_bytes{instance=\"$node_name\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_active_bytes{instance=\"$node_name\"}",
     "legendFormat": "Active (Used)"
    },
    {
     "expr": "node_memory_cache_bytes{instance=\"$node_name\"} + node_memory_buffer_bytes{instance=\"$node_name\"}",
     "legendFormat": "Cache + Buffer"
    },
    {
     "expr": "node_memory_free_bytes{instance=\"$node_name\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_inactive_bytes{instance=\"$node_name\"}",
     "legendFormat": "Inactive"
    },
    {
     "expr": "node_memory_wired_bytes{instance=\"$node_name\"}",
     "legendFormat": "Wired (Kernel)"
    }
   ]
  },
  { "title": "CPU cores usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CPU ALL usage",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (node_name,mode) (clamp_max(((avg by (mode,node_name) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$node_name\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$node_name\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{instance=~\"$node_name\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_average{instance=~\"$node_name\", mode!=\"total\", mode!=\"idle\"}[5m]))),100))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "node_cpu_seconds_total{group=\"Firewall\", cpu=\"1\"} ",
     "legendFormat": "Core 1"
    },
    {
     "expr": "node_cpu_seconds_total{group=\"Firewall\", cpu=\"2\"} ",
     "legendFormat": "Core 2"
    },
    {
     "expr": "node_cpu_seconds_total{group=\"Firewall\", cpu=\"3\"} ",
     "legendFormat": "Core 3"
    },
    {
     "expr": "node_cpu_seconds_total{group=\"Firewall\", cpu=\"4\"} ",
     "legendFormat": "Core 4"
    },
    {
     "expr": "node_cpu_seconds_total{group=\"Firewall\", cpu=\"5\"} ",
     "legendFormat": "Core 5"
    },
    {
     "expr": "node_cpu_seconds_total{group=\"Firewall\", cpu=\"6\"} ",
     "legendFormat": "Core 6"
    },
    {
     "expr": "node_cpu_seconds_total{group=\"Firewall\", cpu=\"7\"} ",
     "legendFormat": "Core 7"
    }
   ]
  },
  { "title": "System Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Context switches / sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_exec_context_switches_total{instance=\"$node_name\"}[$interval])",
     "legendFormat": "Context switches"
    }
   ]
  },
  {
   "title": "Device interrupts / sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_exec_device_interrupts_total{instance=\"$node_name\"}[$interval])",
     "legendFormat": "Device interrupts"
    }
   ]
  },
  {
   "title": "Software interrupts / sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_exec_software_interrupts_total{instance=\"$node_name\"}[$interval])",
     "legendFormat": "Software interrupts"
    }
   ]
  },
  {
   "title": "Exec forks() / sec",
   "type": "timeseries",
   "description": "Number of fork() calls / sec",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_exec_forks_total{instance=\"$node_name\"}[$interval])",
     "legendFormat": "Forks"
    }
   ]
  },
  {
   "title": "Traps / sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_exec_traps_total{instance=\"$node_name\"}[$interval])",
     "legendFormat": "Traps"
    }
   ]
  },
  {
   "title": "System calls / sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_exec_system_calls_total{instance=\"$node_name\"}[$interval])",
     "legendFormat": "Syscalls"
    }
   ]
  }
 ]
}