{
 "title": "ProxySQL Fleet Overview",
 "tags": [ "proxysql" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(proxysql_uptime_seconds_total, instance)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(proxysql_client_connections_connected{instance=~\"$instance\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Active Transactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(proxysql_active_transactions{instance=~\"$instance\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Frontend Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "proxysql_client_connections_connected{instance=~\"$instance\",job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Frontend Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "proxysql_client_connections_connected{instance=~\"$instance\",job=\"$job\"}/proxysql_mysql_max_connections{instance=~\"$instance\",job=\"$job\"}*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Backend Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "proxysql_server_connections_connected{instance=~\"$instance\",job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Frontend vs. Backend Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100-(sum(proxysql_connpool_conns{instance=~\"$instance\",job=\"$job\",status=\"used\"})/sum(proxysql_client_connections_connected{instance=~\"$instance\",job=\"$job\"})*100)",
     "legendFormat": "Multiplexing Efficiency Ratio"
    }
   ]
  },
  {
   "title": "Frontend Connection Overview",
   "type": "graph",
   "gridPos": { "h": 13, "w": 17, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proxysql_client_connections_non_idle{instance=~\"$instance\",job=\"$job\"}",
     "legendFormat": "{{instance}} (used)"
    },
    {
     "expr": "proxysql_client_connections_connected{instance=~\"$instance\",job=\"$job\"}-proxysql_client_connections_non_idle{instance=~\"$instance\",job=\"$job\"}",
     "legendFormat": "{{instance}} (idle)"
    }
   ]
  },
  {
   "title": "Connection Overview",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(proxysql_client_connections_connected{instance=~\"$instance\",job=\"$job\"})",
     "legendFormat": "Total Frontend Connections"
    },
    {
     "expr": "sum(proxysql_connpool_conns{instance=~\"$instance\",job=\"$job\",status=\"used\"})",
     "legendFormat": "Total Backend Connections (in-use)"
    },
    {
     "expr": "sum(proxysql_connpool_conns{instance=~\"$instance\",job=\"$job\",status=\"free\"})",
     "legendFormat": "Total Backend Connections (free)"
    }
   ]
  },
  {
   "title": "Total Send / Receive Rates",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(proxysql_queries_frontends_bytes_total{instance=~\"$instance\",job=\"$job\",traffic_flow=\"sent\"}[$__rate_interval]))",
     "legendFormat": "Frontend Send Rate"
    },
    {
     "expr": "sum(irate(proxysql_queries_frontends_bytes_total{traffic_flow=\"received\",instance=~\"$instance\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Frontend Receive Rate"
    },
    {
     "expr": "sum(irate(proxysql_queries_backends_bytes_total{traffic_flow=\"sent\",instance=~\"$instance\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Backend Send Rate"
    },
    {
     "expr": "sum(irate(proxysql_queries_backends_bytes_total{traffic_flow=\"received\",instance=~\"$instance\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Backend Receive Rate"
    }
   ]
  },
  {
   "title": "Backend Connection Overview",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(proxysql_connpool_conns{instance=~\"$instance\",job=\"$job\",status=\"used\"}) by (endpoint)",
     "legendFormat": "{{endpoint}} (used)"
    },
    {
     "expr": "sum(proxysql_connpool_conns{instance=~\"$instance\",job=\"$job\",status=\"free\"}) by (endpoint)",
     "legendFormat": "{{endpoint}} (free)"
    }
   ]
  }
 ]
}