{
 "title": "Node",
 "tags": [ "diz-sys" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Gruppe:",
    "query": {
     "query": "label_values(up{job=\"node\"}, group)"
    }
   },
   {
    "name": "node_type",
    "label": "Node Type:",
    "query": {
     "query": "label_values(up{job=\"node\", group=~\"$group\"}, node_type)"
    }
   },
   {
    "name": "node",
    "label": "Node:",
    "query": {
     "query": "label_values(up{job=\"node\", group=~\"$group\", node_type=~\"$node_type\"}, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node parameters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# CPU cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (group by (node, cpu) (node_cpu_seconds_total{node=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "RAM total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Swap total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{node=~\"$node\"}"
    }
   ]
  },
  {
   "title": "root-FS total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{node=~\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu_seconds_total{node=~\"$node\"}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "round(sum by (node) (irate(node_cpu_seconds_total{node=~\"$node\"}[5m])))",
     "legendFormat": "available CPUs"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "description": "Average busy state over all CPU cores",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - avg (irate(node_cpu_seconds_total{mode=\"idle\",node=\"$node\"}[5m]))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "bargauge",
   "description": "Relative RAM usage",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes{node=~\"$node\"} / node_memory_MemTotal_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "bargauge",
   "description": "Relative swap usage",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (node_memory_SwapFree_bytes{node=~\"$node\"} / node_memory_SwapTotal_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "root-FS",
   "type": "bargauge",
   "description": "Relative usage of the root file system",
   "gridPos": { "h": 8, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{node=~\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"} / node_filesystem_size_bytes{node=~\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$node\"}",
     "legendFormat": "MemTotal"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=~\"$node\"}",
     "legendFormat": "MemFree"
    },
    {
     "expr": "node_memory_Cached_bytes{node=~\"$node\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_Buffers_bytes{node=~\"$node\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{node=~\"$node\"}",
     "legendFormat": "SwapTotal"
    },
    {
     "expr": "node_memory_SwapFree_bytes{node=~\"$node\"}",
     "legendFormat": "SwapFree"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{node=~\"$node\"} - node_boot_time_seconds{node=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Last reboot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_boot_time_seconds{node=~\"$node\"} * 1000"
    }
   ]
  },
  { "title": "fail2ban", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fail2ban_up{node=~\"$node\"}"
    }
   ]
  },
  {
   "title": "# banned IPs (cur.)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fail2ban_banned_ips{node=~\"$node\"}"
    }
   ]
  },
  {
   "title": "# banned IPs (tot.)",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "fail2ban_currently_banned{job=\"fail2ban\", group=~\"$group\", node_type=~\"$node_type\", node=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Jails",
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 9, "y": 16 },
   "targets": [
    {
     "expr": "fail2ban_enabled_jails{node=~\"$node\"}"
    }
   ]
  }
 ]
}