{
 "title": "cert-manager",
 "tags": [
  "Kubernetes",
  "Prometheus",
  "cert-manager"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(certmanager_certificate_ready_status, job)"
    }
   },
   {
    "name": "exported_namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(certmanager_certificate_ready_status{job=~\"$job\"}, exported_namespace)"
    }
   },
   {
    "name": "name",
    "label": "Certificate",
    "query": {
     "query": "label_values(certmanager_certificate_ready_status{job=~\"$job\", exported_namespace=~\"$exported_namespace\"},name) "
    }
   },
   { "name": "critical_threshold", "label": "Critical Threshold (days)", "query": "1,7,14,15,28,30,60,90,180,365" },
   { "name": "warning_threshold", "label": "Warning Threshold (days)", "query": "1,7,14,15,28,30,60,90,180,365" },
   {
    "name": "list_threshold",
    "label": "List expiring in less than (days)",
    "query": "1,7,14,15,28,30,60,90,180,365"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Certificates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(certmanager_certificate_expiration_timestamp_seconds{job=~\"$job\", exported_namespace=~\"$exported_namespace\"})"
    }
   ]
  },
  {
   "title": "By Namespaces",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(certmanager_certificate_expiration_timestamp_seconds{job=~\"$job\", exported_namespace=~\"$exported_namespace\", name=~\"$name\"}) by (exported_namespace)",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Expired",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((certmanager_certificate_expiration_timestamp_seconds{job=~\"$job\", exported_namespace=~\"$exported_namespace\", name=~\"$name\"} - time()) / 86400) < bool 0)"
    }
   ]
  },
  {
   "title": "Expiring within $critical_threshold days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(0 < ((certmanager_certificate_expiration_timestamp_seconds{job=~\"$job\", exported_namespace=~\"$exported_namespace\", name=~\"$name\"} - time()) / 86400) < bool $critical_threshold)"
    }
   ]
  },
  {
   "title": "Expiring within $warning_threshold days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(0 < ((certmanager_certificate_expiration_timestamp_seconds{job=~\"$job\", exported_namespace=~\"$exported_namespace\", name=~\"$name\"} - time()) / 86400) < bool $warning_threshold)"
    }
   ]
  },
  {
   "title": "Shortest validity [days]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(certmanager_certificate_expiration_timestamp_seconds{job=~\"$job\", exported_namespace=~\"$exported_namespace\", name=~\"$name\"} - time()) / 86400"
    }
   ]
  },
  {
   "title": "Longest validity [days]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(certmanager_certificate_expiration_timestamp_seconds{job=~\"$job\", exported_namespace=~\"$exported_namespace\", name=~\"$name\"} - time()) / 86400"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(certmanager_http_acme_client_request_count{job=~\"$job\", exported_namespace=~\"$exported_namespace\", name=~\"$name\", status=~\"^4.+\"})"
    }
   ]
  },
  { "title": "Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Validity",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$exported_namespace\", name=~\"$name\"} - time()) < ($list_threshold * 86400)",
     "legendFormat": " {{exported_namespace}} / {{name}}"
    },
    {}
   ]
  },
  {
   "title": "Certificate Ready Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(certmanager_certificate_ready_status{exported_namespace=~\"$exported_namespace\", name=~\"$name\"}) BY (condition)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Time Left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$exported_namespace\", name=~\"$name\"} - time()) BY (name,exported_namespace)",
     "legendFormat": " {{exported_namespace}} / {{name}}"
    }
   ]
  },
  { "title": "ACME Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Overall requests per 2m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(certmanager_http_acme_client_request_count)"
    }
   ]
  },
  {
   "title": "/directory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/directory\"}[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "/acme/cert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/cert\"}[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "/acme/new-acct",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/new-acct\"}[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "/acme/order",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/order\"}[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "/acme/new-order",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/new-order\"}[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "/acme/authz-v3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/authz-v3\"}[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "/acme/chall-v3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/chall-v3\"}[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "/acme/finalize",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/finalize\"}[2m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}