{
 "title": "Blackbox Exporter",
 "tags": [
  "Blackbox",
  "Prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(probe_success, job)"
    }
   },
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\"}, target)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Targets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(count(probe_success{job=~\"$job\"}))"
    }
   ]
  },
  {
   "title": "Probes Success Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_success{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Probes SSL Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(probe_http_ssl{job=~\"$job\"} == 1) / count(probe_http_version{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Global Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=~\"$job\"}",
     "legendFormat": "{{ target }}"
    }
   ]
  },
  { "title": "$target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "target" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\", target=~\"$target\"}"
    }
   ]
  },
  {
   "title": "Uptime %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\", target=~\"$target\"}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=~\"$job\", target=~\"$target\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{job=~\"$job\", target=~\"$target\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Latest HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=~\"$job\", target=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{job=~\"$job\", target=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{job=~\"$job\", target=~\"$target\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "SSL Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_tls_version_info{job=~\"$job\", target=~\"$target\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "SSL Certificate Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{job=~\"$job\", target=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=~\"$job\", target=~\"$target\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=~\"$job\", target=~\"$target\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{job=~\"$job\", target=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{job=~\"$job\", target=~\"$target\"})"
    }
   ]
  }
 ]
}