{
 "title": "certificates",
 "tags": [
  "Prometheus",
  "blackbox-exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job:",
    "query": {
     "query": "label_values(probe_success, job)"
    }
   },
   {
    "name": "target",
    "label": "Target:",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\"}, target)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Überblick", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Domains (gesamt)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{job=~\"$job\", target=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Erfolgreiche SSL-Verbindung",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_http_ssl{job=~\"$job\", target=~\"$target\"} == 1)"
    }
   ]
  },
  {
   "title": "Fehlgeschlagene SSL-Verbindung",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_http_ssl{job=~\"$job\", target=~\"$target\"} == 0)"
    }
   ]
  },
  {
   "title": "Auslaufende SSL-Zertifikate (2w)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_ssl_earliest_cert_expiry{job=~\"$job\", target=~\"$target\"}-time() < 1296000)"
    }
   ]
  },
  {
   "title": "Auslaufende SSL-Zertifikate (1w)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_ssl_earliest_cert_expiry{job=~\"$job\", target=~\"$target\"}-time() < 691200)"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Certificates",
   "type": "table",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(probe_http_ssl{job=~\"$job\", target=~\"$target\"}) by (target)"
    },
    {
     "expr": "sum(probe_ssl_earliest_cert_expiry{job=~\"$job\", target=~\"$target\"}-time()) by (target)"
    },
    {
     "expr": "sum(probe_http_status_code{job=~\"$job\", target=~\"$target\"}) by (target)"
    }
   ]
  }
 ]
}